title: <p align="center"> Harish Rathuri </p>
logo: /assets/img/HarishPhoto.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/harish-rathuri-1a813b52/">LinkedIn</a> |
  <a href="https://github.com/harryraturi">GitHub</a>
  
  <br>   
  I'm learning Machine Learning & AI.
  Also I've 12+ years of experience in Mobile Application Development.
  <br>
  </p>



theme: jekyll-theme-minimal
